In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import sqlite3

In [3]:
df_csv = pd.read_csv("data.CSV")
df_csv.head()

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [7]:
df_excel = pd.read_excel("data.xlsx",sheet_name= 0)

In [6]:
df_json = pd.read_json("data.json")
df_json

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris

In [9]:
conn = sqlite3.connect("example.db")
df_sql = pd.read_sql_query("SELECT * FROM my_table",conn)
df_sql

   id     name  age      city
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   35     Paris