In [10]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [2]:
df = pd.DataFrame({
    'colors':["red","blue","Green","blue","red"],
    'shape':["Circle","square","Triangle","circle","Square"]
})
df

  colors     shape
0    red    Circle
1   blue    square
2  Green  Triangle
3   blue    circle
4    red    Square

In [3]:
df1 = df.copy()

In [4]:
le = LabelEncoder()
df["colors"] = le.fit_transform(df["colors"])  
df["shape"] = le.fit_transform(df['shape'])
df

   colors  shape
0       2      0
1       1      4
2       0      2
3       1      3
4       2      1

In [5]:
df1

  colors     shape
0    red    Circle
1   blue    square
2  Green  Triangle
3   blue    circle
4    red    Square

In [6]:
df_encoded_pandas = pd.get_dummies(df1,columns=['colors','shape'])
df_encoded_pandas

,colors_Green,colors_blue,colors_red,shape_Circle,shape_Square,shape_Triangle,shape_circle,shape_square
0,False,False,True,True,False,False,False,False
1,False,True,False,False,False,False,False,True
2,True,False,False,False,False,True,False,False
3,False,True,False,False,False,False,True,False
4,False,False,True,False,True,False,False,False

In [9]:
df_encoded_pandas = pd.get_dummies(df1,columns=['colors','shape'],dtype=np.int32, drop_first=True)
df_encoded_pandas

,colors_blue,colors_red,shape_Square,shape_Triangle,shape_circle,shape_square
0,0,1,0,0,0,0
1,1,0,0,0,0,1
2,0,0,0,1,0,0
3,1,0,0,0,1,0
4,0,1,1,0,0,0

In [19]:
ds = pd.DataFrame({
    'Size':['Small','mediam','large','small'],
    "education":['primary','secandary','graduate','postgraduate']
})

In [20]:
ds

     Size     education
0   Small       primary
1  mediam     secandary
2   large      graduate
3   small  postgraduate

In [29]:
oe_size = OrdinalEncoder(categories=[['small','mediam','large']])
ds['new_size'] = oe_size.fit_transform(ds[['Size']])

In [30]:
ds

     Size     education  new_size  new_education
0   small       primary       0.0            0.0
1  mediam     secondary       1.0            1.0
2   large      graduate       2.0            2.0
3   small  postgraduate       0.0            3.0

In [28]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

ds = pd.DataFrame({
    'Size': ['Small', 'mediam', 'large', 'small'],
    'education': ['primary', 'secondary', 'graduate', 'postgraduate']
})

# Fix 1: categories list of lists mein honi chahiye
# Fix 2: case match karna zaroori hai — 'Small' != 'small'
oe_size = OrdinalEncoder(categories=[['small', 'mediam', 'large']])
ds['Size'] = ds['Size'].str.lower()  # Sab lowercase kar do
ds['new_size'] = oe_size.fit_transform(ds[['Size']])

# Education bhi encode karo
oe_edu = OrdinalEncoder(categories=[['primary', 'secondary', 'graduate', 'postgraduate']])
ds['new_education'] = oe_edu.fit_transform(ds[['education']])

print(ds)

     Size     education  new_size  new_education
0   small       primary       0.0            0.0
1  mediam     secondary       1.0            1.0
2   large      graduate       2.0            2.0
3   small  postgraduate       0.0            3.0