* 13:36Summary: Imputation Strategies
* StrategyBest ForAvoid WhenMeanNormal numeric data, few missingOutliers hoMedianSkewed numeric, outliers hoCategorical
* dataModeCategorical columnsNumeric continuous dataRandomDistribution preserve karnaSmall datasets

In [17]:
import pandas as pd
import numpy as np

data = {
    'name': ['Ali', 'Sara', 'Ahmed', 'Fatima', 'Usman', 'Ayesha', 'Bilal', 'Zara'],
    'age': [25, np.nan, 35, 28, np.nan, 42, 30, np.nan],
    'salary': [50000, 60000, np.nan, 45000, 70000, np.nan, 55000, 48000],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'HR'],
    'city': ['Karachi', 'Lahore', np.nan, 'Karachi', 'Lahore', np.nan, 'Karachi', np.nan]
}

df = pd.DataFrame(data)
print(df)

     name   age   salary department     city
0     Ali  25.0  50000.0         HR  Karachi
1    Sara   NaN  60000.0         IT   Lahore
2   Ahmed  35.0      NaN    Finance      NaN
3  Fatima  28.0  45000.0         IT  Karachi
4   Usman   NaN  70000.0         HR   Lahore
5  Ayesha  42.0      NaN    Finance      NaN
6   Bilal  30.0  55000.0         IT  Karachi
7    Zara   NaN  48000.0         HR      NaN

In [9]:
from sklearn.impute import SimpleImputer

In [10]:
mean_imputer = SimpleImputer(strategy='mean')
df_mean = df.copy()
df_mean[['age','salary']] = mean_imputer.fit_transform(df_mean[['age','salary']])
print("\n Imputed mean data:")
display(df_mean)

 Imputed mean data:

     name   age        salary department     city
0     Ali  25.0  50000.000000         HR  Karachi
1    Sara  32.0  60000.000000         IT   Lahore
2   Ahmed  35.0  54666.666667    Finance      NaN
3  Fatima  28.0  45000.000000         IT  Karachi
4   Usman  32.0  70000.000000         HR   Lahore
5  Ayesha  42.0  54666.666667    Finance      NaN
6   Bilal  30.0  55000.000000         IT  Karachi
7    Zara  32.0  48000.000000         HR      NaN

In [11]:
median_imputer = SimpleImputer(strategy='median')
df_median = df.copy()
df_median[['age','salary']] = mean_imputer.fit_transform(df_median[['age','salary']])
print("\n Imputed median data:")
display(df_median)

 Imputed median data:

     name   age        salary department     city
0     Ali  25.0  50000.000000         HR  Karachi
1    Sara  32.0  60000.000000         IT   Lahore
2   Ahmed  35.0  54666.666667    Finance      NaN
3  Fatima  28.0  45000.000000         IT  Karachi
4   Usman  32.0  70000.000000         HR   Lahore
5  Ayesha  42.0  54666.666667    Finance      NaN
6   Bilal  30.0  55000.000000         IT  Karachi
7    Zara  32.0  48000.000000         HR      NaN

In [18]:
mode_imputer = SimpleImputer(strategy='most_frequent')
df_mode = df.copy()
df_mode[['city']] = mode_imputer.fit_transform(df_mode[['city']])
print("\n Imputed mode data:")
display(df_mode) # this is the jupyter notebook function which is used for showing the table

 Imputed mode data:

     name   age   salary department     city
0     Ali  25.0  50000.0         HR  Karachi
1    Sara   NaN  60000.0         IT   Lahore
2   Ahmed  35.0      NaN    Finance  Karachi
3  Fatima  28.0  45000.0         IT  Karachi
4   Usman   NaN  70000.0         HR   Lahore
5  Ayesha  42.0      NaN    Finance  Karachi
6   Bilal  30.0  55000.0         IT  Karachi
7    Zara   NaN  48000.0         HR  Karachi

In [15]:
import random
df_random = df.copy()
def random_impute(series):
    filled = series.dropna().tolist()
    return series.apply(lambda x: random.choice(filled) if pd.isnull(x) else x)

for col in ['age','salary','city']:
    df_random[col] = random_impute(df_random[col])

print("\n random impute data :")
display(df_random)

 random impute data :

     name   age   salary department     city
0     Ali  25.0  50000.0         HR  Karachi
1    Sara  25.0  60000.0         IT   Lahore
2   Ahmed  35.0  60000.0    Finance   Lahore
3  Fatima  28.0  45000.0         IT  Karachi
4   Usman  42.0  70000.0         HR   Lahore
5  Ayesha  42.0  70000.0    Finance  Karachi
6   Bilal  30.0  55000.0         IT  Karachi
7    Zara  35.0  48000.0         HR  Karachi

< 5%   → Mean/Median/Mode ✅
5-20%  → Median/Mode ✅
20-40% → Random/ML based ⚠️
40%+   → Drop column ❌