In [3]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder,OneHotEncoder,TargetEncoder

In [4]:
ds = pd.read_csv('PROPERTIES.csv')
ds

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

In [5]:
ds['Review'].value_counts()

Review
Good       6
Average    5
Poor       2
Name: count, dtype: int64

In [6]:
le = LabelEncoder()

# label Encoder

In [7]:
le_in_review = le.fit_transform(ds[['Review']])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [9]:
le_in_review

array([2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1])

In [8]:
ds

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

# ordinal encoder

In [12]:
c = {'poor':0,'Average':1,'Good':2}
encode_review_ordinal = ds['Review'].map(c)
encode_review_ordinal

0     NaN
1     1.0
2     2.0
3     1.0
4     1.0
5     2.0
6     2.0
7     2.0
8     2.0
9     NaN
10    1.0
11    1.0
12    2.0
Name: Review, dtype: float64

# execute with the help of sklearn

In [15]:
data3 = ds.copy()

In [24]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good']])
data3['Review'] = oe.fit_transform(data3[['Review']])

In [25]:
# data3

         Area    Sqft   Price  Review
0    MP NAGAR  2600.0  550000     0.0
1    MP NAGAR     NaN  565000     1.0
2    MP NAGAR  3200.0  610000     2.0
3    MP NAGAR  3600.0  680000     1.0
4    MP NAGAR  4000.0  725000     1.0
5     NEW MKT  2600.0  585000     2.0
6     NEW MKT  2800.0  615000     2.0
7     NEW MKT  3300.0  650000     2.0
8     NEW MKT  3600.0  710000     2.0
9   INDRAPURI  2600.0  575000     0.0
10  INDRAPURI  2900.0  600000     1.0
11  INDRAPURI  3100.0  620000     1.0
12  INDRAPURI  3600.0  695000     2.0

In [37]:
# len_ = int(input("enter your number :-"))
# for i in range(len_):
#     print(i*'❤️')

enter your number :- 6

❤️
❤️❤️
❤️❤️❤️
❤️❤️❤️❤️
❤️❤️❤️❤️❤️