In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [7]:
ds = pd.read_csv('retail_sales_dataset.csv')
ds

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [8]:
ds['Age'].max()

64

In [9]:
ds['Age'].min()

18

# extract the age columns

In [10]:
bins = [18,35,50,70,90]
labels = ['young','middle','senior','old age']
ds['age_group'] = pd.cut(ds['Age'], bins = bins,labels= labels)
ds[['Age','age_group']]

     Age age_group
0     34     young
1     26     young
2     50    middle
3     37    middle
4     30     young
..   ...       ...
995   62    senior
996   52    senior
997   23     young
998   36    middle
999   47    middle

[1000 rows x 2 columns]

In [11]:
ds.loc[ds['age_group'] == 'middle', ['Age', 'age_group']]

     Age age_group
2     50    middle
3     37    middle
5     45    middle
6     46    middle
14    42    middle
..   ...       ...
988   44    middle
992   48    middle
994   41    middle
998   36    middle
999   47    middle

[313 rows x 2 columns]

In [12]:
ds['Year'] = pd.to_datetime(ds['Date']).dt.year
ds['Year']

0      2023
1      2023
2      2023
3      2023
4      2023
       ...
995    2023
996    2023
997    2023
998    2023
999    2023
Name: Year, Length: 1000, dtype: int32

In [13]:
ds['month'] = pd.to_datetime(ds['Date']).dt.month
ds['month']

0      11
1       2
2       1
3       5
4       5
       ..
995     5
996    11
997    10
998    12
999     4
Name: month, Length: 1000, dtype: int32

In [14]:
ds['day'] = pd.to_datetime(ds['Date']).dt.day
ds['day']

0      24
1      27
2      13
3      21
4       6
       ..
995    16
996    17
997    29
998     5
999    12
Name: day, Length: 1000, dtype: int32

In [15]:
ds

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,age_group,Year,month,day
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,young,2023,11,24
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,young,2023,2,27
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,middle,2023,1,13
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,middle,2023,5,21
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,young,2023,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,senior,2023,5,16
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,senior,2023,11,17
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,young,2023,10,29
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,middle,2023,12,5
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,middle,2023,4,12

# create a name columns in this column add mr joy sinha

# this process is called feature splitting

In [16]:
ds['name'] = 'mr joy sinha'
ds

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,age_group,Year,month,day,name
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,young,2023,11,24,mr joy sinha
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,young,2023,2,27,mr joy sinha
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,middle,2023,1,13,mr joy sinha
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,middle,2023,5,21,mr joy sinha
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,young,2023,5,6,mr joy sinha
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,senior,2023,5,16,mr joy sinha
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,senior,2023,11,17,mr joy sinha
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,young,2023,10,29,mr joy sinha
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,middle,2023,12,5,mr joy sinha
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,middle,2023,4,12,mr joy sinha

"mr joy sinha"
    |
.split(" ")
    ↓
["mr", "joy", "sinha"]
    |
expand=True
    ↓
mr | joy | sinha
    |
assign to columns

# create three column intial, first and last and fill with mr , joy and sinha

In [28]:
ds[['initial','first','last']] = ds['name'].str.split(' ',expand= True)

In [33]:
# apply is used for fuction as a parameter in the apply 
# ds['initi'] = ds['name'].apply(lambda x: x.split()[0])
# ds['initi'] = ds['name'].apply(lambda x: x.split()[1])
# ds['initi'] = ds['name'].apply(lambda x: x.split()[2])

In [32]:
ds

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,age_group,Year,month,day,name,initial,first,last
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,young,2023,11,24,mr joy sinha,mr,joy,sinha
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,young,2023,2,27,mr joy sinha,mr,joy,sinha
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,middle,2023,1,13,mr joy sinha,mr,joy,sinha
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,middle,2023,5,21,mr joy sinha,mr,joy,sinha
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,young,2023,5,6,mr joy sinha,mr,joy,sinha
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50,senior,2023,5,16,mr joy sinha,mr,joy,sinha
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90,senior,2023,11,17,mr joy sinha,mr,joy,sinha
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100,young,2023,10,29,mr joy sinha,mr,joy,sinha
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150,middle,2023,12,5,mr joy sinha,mr,joy,sinha
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120,middle,2023,4,12,mr joy sinha,mr,joy,sinha

# create a new column last purchases year on the bases of data column

In [49]:
ds['Last_Purchase_Year'] = pd.to_datetime(ds['Date']).dt.year

In [37]:
ds['Last_Purchase_Year']

0      2023
1      2023
2      2023
3      2023
4      2023
       ...
995    2023
996    2023
997    2023
998    2023
999    2023
Name: Last_Purchase_Year, Length: 1000, dtype: int32

In [ ]:
showing the es na kab apna last purchase kya tha

In [51]:
current_year = pd.Timestamp.now().year
ds['Years_Since_Purchase'] = current_year - ds['Last_Purchase_Year']

In [53]:
ds.head(30)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,age_group,Year,month,day,name,initial,first,last,Last_Purchase_Year,Years_Since_Purchase
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,young,2023,11,24,mr joy sinha,mr,joy,sinha,2023,3
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,young,2023,2,27,mr joy sinha,mr,joy,sinha,2023,3
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,middle,2023,1,13,mr joy sinha,mr,joy,sinha,2023,3
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,middle,2023,5,21,mr joy sinha,mr,joy,sinha,2023,3
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,young,2023,5,6,mr joy sinha,mr,joy,sinha,2023,3
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30,middle,2023,4,25,mr joy sinha,mr,joy,sinha,2023,3
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50,middle,2023,3,13,mr joy sinha,mr,joy,sinha,2023,3
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100,young,2023,2,22,mr joy sinha,mr,joy,sinha,2023,3
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600,senior,2023,12,13,mr joy sinha,mr,joy,sinha,2023,3
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200,senior,2023,10,7,mr joy sinha,mr,joy,sinha,2023,3
10,11,2023-02-14,CUST011,Male,23,Clothing,2,50,100,young,2023,2,14,mr joy sinha,mr,joy,sinha,2023,3
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75,young,2023,10,30,mr joy sinha,mr,joy,sinha,2023,3
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500,young,2023,8,5,mr joy sinha,mr,joy,sinha,2023,3
13,14,2023-01-17,CUST014,Male,64,Clothing,4,30,120,senior,2023,1,17,mr joy sinha,mr,joy,sinha,2023,3
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000,middle,2023,1,16,mr joy sinha,mr,joy,sinha,2023,3
15,16,2023-02-17,CUST016,Male,19,Clothing,3,500,1500,young,2023,2,17,mr joy sinha,mr,joy,sinha,2023,3
16,17,2023-04-22,CUST017,Female,27,Clothing,4,25,100,young,2023,4,22,mr joy sinha,mr,joy,sinha,2023,3
17,18,2023-04-30,CUST018,Female,47,Electronics,2,25,50,middle,2023,4,30,mr joy sinha,mr,joy,sinha,2023,3
18,19,2023-09-16,CUST019,Female,62,Clothing,2,25,50,senior,2023,9,16,mr joy sinha,mr,joy,sinha,2023,3
19,20,2023-11-05,CUST020,Male,22,Clothing,3,300,900,young,2023,11,5,mr joy sinha,mr,joy,sinha,2023,3
20,21,2023-01-14,CUST021,Female,50,Beauty,1,500,500,middle,2023,1,14,mr joy sinha,mr,joy,sinha,2023,3
21,22,2023-10-15,CUST022,Male,18,Clothing,2,50,100,NaN,2023,10,15,mr joy sinha,mr,joy,sinha,2023,3
22,23,2023-04-12,CUST023,Female,35,Clothing,4,30,120,young,2023,4,12,mr joy sinha,mr,joy,sinha,2023,3
23,24,2023-11-29,CUST024,Female,49,Clothing,1,300,300,middle,2023,11,29,mr joy sinha,mr,joy,sinha,2023,3
24,25,2023-12-26,CUST025,Female,64,Beauty,1,50,50,senior,2023,12,26,mr joy sinha,mr,joy,sinha,2023,3
25,26,2023-10-07,CUST026,Female,28,Electronics,2,500,1000,young,2023,10,7,mr joy sinha,mr,joy,sinha,2023,3
26,27,2023-08-03,CUST027,Female,38,Beauty,2,25,50,middle,2023,8,3,mr joy sinha,mr,joy,sinha,2023,3
27,28,2023-04-23,CUST028,Female,43,Beauty,1,500,500,middle,2023,4,23,mr joy sinha,mr,joy,sinha,2023,3
28,29,2023-08-18,CUST029,Female,42,Electronics,1,30,30,middle,2023,8,18,mr joy sinha,mr,joy,sinha,2023,3
29,30,2023-10-29,CUST030,Female,39,Beauty,3,300,900,middle,2023,10,29,mr joy sinha,mr,joy,sinha,2023,3