In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
ds = pd.read_csv('PROPERTIES.csv')
ds

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

In [3]:
ds['Area'].value_counts()

Area
MP NAGAR     5
NEW MKT      4
INDRAPURI    4
Name: count, dtype: int64

In [4]:
ds1 = pd.get_dummies(ds,columns=['Area'], drop_first = True, dtype = np.int32)
# remove the first column for create  independance

In [5]:
ds1

      Sqft   Price   Review  Area_MP NAGAR  Area_NEW MKT
0   2600.0  550000     Poor              1             0
1      NaN  565000  Average              1             0
2   3200.0  610000     Good              1             0
3   3600.0  680000  Average              1             0
4   4000.0  725000  Average              1             0
5   2600.0  585000     Good              0             1
6   2800.0  615000     Good              0             1
7   3300.0  650000     Good              0             1
8   3600.0  710000     Good              0             1
9   2600.0  575000     Poor              0             0
10  2900.0  600000  Average              0             0
11  3100.0  620000  Average              0             0
12  3600.0  695000     Good              0             0

In [6]:
ds_stacked = pd.concat([ds, ds1], axis=0, ignore_index=True)

In [7]:
ds_stacked

         Area    Sqft   Price   Review  Area_MP NAGAR  Area_NEW MKT
0    MP NAGAR  2600.0  550000     Poor            NaN           NaN
1    MP NAGAR     NaN  565000  Average            NaN           NaN
2    MP NAGAR  3200.0  610000     Good            NaN           NaN
3    MP NAGAR  3600.0  680000  Average            NaN           NaN
4    MP NAGAR  4000.0  725000  Average            NaN           NaN
5     NEW MKT  2600.0  585000     Good            NaN           NaN
6     NEW MKT  2800.0  615000     Good            NaN           NaN
7     NEW MKT  3300.0  650000     Good            NaN           NaN
8     NEW MKT  3600.0  710000     Good            NaN           NaN
9   INDRAPURI  2600.0  575000     Poor            NaN           NaN
10  INDRAPURI  2900.0  600000  Average            NaN           NaN
11  INDRAPURI  3100.0  620000  Average            NaN           NaN
12  INDRAPURI  3600.0  695000     Good            NaN           NaN
13        NaN  2600.0  550000     Poor            1.0           0.0
14        NaN     NaN  565000  Average            1.0           0.0
15        NaN  3200.0  610000     Good            1.0           0.0
16        NaN  3600.0  680000  Average            1.0           0.0
17        NaN  4000.0  725000  Average            1.0           0.0
18        NaN  2600.0  585000     Good            0.0           1.0
19        NaN  2800.0  615000     Good            0.0           1.0
20        NaN  3300.0  650000     Good            0.0           1.0
21        NaN  3600.0  710000     Good            0.0           1.0
22        NaN  2600.0  575000     Poor            0.0           0.0
23        NaN  2900.0  600000  Average            0.0           0.0
24        NaN  3100.0  620000  Average            0.0           0.0
25        NaN  3600.0  695000     Good            0.0           0.0

In [8]:
final = np.hstack([ds,ds1])

In [9]:
final

array([['MP NAGAR', 2600.0, 550000, 'Poor', 2600.0, 550000, 'Poor', 1, 0],
       ['MP NAGAR', nan, 565000, 'Average', nan, 565000, 'Average', 1, 0],
       ['MP NAGAR', 3200.0, 610000, 'Good', 3200.0, 610000, 'Good', 1, 0],
       ['MP NAGAR', 3600.0, 680000, 'Average', 3600.0, 680000, 'Average',
        1, 0],
       ['MP NAGAR', 4000.0, 725000, 'Average', 4000.0, 725000, 'Average',
        1, 0],
       ['NEW MKT', 2600.0, 585000, 'Good', 2600.0, 585000, 'Good', 0, 1],
       ['NEW MKT', 2800.0, 615000, 'Good', 2800.0, 615000, 'Good', 0, 1],
       ['NEW MKT', 3300.0, 650000, 'Good', 3300.0, 650000, 'Good', 0, 1],
       ['NEW MKT', 3600.0, 710000, 'Good', 3600.0, 710000, 'Good', 0, 1],
       ['INDRAPURI', 2600.0, 575000, 'Poor', 2600.0, 575000, 'Poor', 0,
        0],
       ['INDRAPURI', 2900.0, 600000, 'Average', 2900.0, 600000,
        'Average', 0, 0],
       ['INDRAPURI', 3100.0, 620000, 'Average', 3100.0, 620000,
        'Average', 0, 0],
       ['INDRAPURI', 3600.0, 695000, 'Good', 3600.0, 695000, 'Good', 0,
        0]], dtype=object)

In [10]:
ds

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

In [11]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False,drop='first')
result = ohe.fit_transform(ds[['Area']]) #.toarray()
result

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
ds.columns

Index(['Area', 'Sqft', 'Price', 'Review'], dtype='object')

In [18]:
pd.DataFrame(np.hstack((result,ds[['Sqft','Price','Review']])),columns=['shinchan','raju','harry','Pk','ladla'])

   shinchan raju   harry      Pk    ladla
0       1.0  0.0  2600.0  550000     Poor
1       1.0  0.0     NaN  565000  Average
2       1.0  0.0  3200.0  610000     Good
3       1.0  0.0  3600.0  680000  Average
4       1.0  0.0  4000.0  725000  Average
5       0.0  1.0  2600.0  585000     Good
6       0.0  1.0  2800.0  615000     Good
7       0.0  1.0  3300.0  650000     Good
8       0.0  1.0  3600.0  710000     Good
9       0.0  0.0  2600.0  575000     Poor
10      0.0  0.0  2900.0  600000  Average
11      0.0  0.0  3100.0  620000  Average
12      0.0  0.0  3600.0  695000     Good

In [19]:
ds

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

# frequency encoder

* Frequency Encoding (also called Count Encoding) converts each category into the number of times it appears in the dataset.

* Frequency Encoding replaces each category with the number of times it appears in the dataset. It helps
  * handle high-cardinality features without increasing dimensionality.”

# ✅ Why is Frequency Encoding used?
* Works well for high-cardinality categorical columns
* Faster than one-hot encoding
* Avoids creating too many dummy columns
* Useful for tree-based models (Random Forest, XGBoost, LightGBM)

In [28]:
df = ds.copy()

In [29]:
freq = df['Area'].value_counts()
freq

Area
MP NAGAR     5
NEW MKT      4
INDRAPURI    4
Name: count, dtype: int64

In [34]:
df['Area'] = df['Area'].map(freq)

In [27]:
df

    Area    Sqft   Price   Review
0    NaN  2600.0  550000     Poor
1    NaN     NaN  565000  Average
2    NaN  3200.0  610000     Good
3    NaN  3600.0  680000  Average
4    NaN  4000.0  725000  Average
5    NaN  2600.0  585000     Good
6    NaN  2800.0  615000     Good
7    NaN  3300.0  650000     Good
8    NaN  3600.0  710000     Good
9    NaN  2600.0  575000     Poor
10   NaN  2900.0  600000  Average
11   NaN  3100.0  620000  Average
12   NaN  3600.0  695000     Good

In [38]:
ds

         Area    Sqft   Price   Review
0    MP NAGAR  2600.0  550000     Poor
1    MP NAGAR     NaN  565000  Average
2    MP NAGAR  3200.0  610000     Good
3    MP NAGAR  3600.0  680000  Average
4    MP NAGAR  4000.0  725000  Average
5     NEW MKT  2600.0  585000     Good
6     NEW MKT  2800.0  615000     Good
7     NEW MKT  3300.0  650000     Good
8     NEW MKT  3600.0  710000     Good
9   INDRAPURI  2600.0  575000     Poor
10  INDRAPURI  2900.0  600000  Average
11  INDRAPURI  3100.0  620000  Average
12  INDRAPURI  3600.0  695000     Good

# target encoder used in the classification problem in the target column

*  ✅ What is Target Encoding?
* Target Encoding replaces each category with the mean of the target variable for that category.
* It is mostly used for classification or regression when you have categorical columns.

| City   | Buy_House (Target) |
| ------ | ------------------ |
| Delhi  | 1                  |
| Delhi  | 0                  |
| Delhi  | 1                  |
| Mumbai | 0                  |
| Mumbai | 0                  |
| Pune   | 1                  |

Now calculate mean target per category:
Delhi: (1 + 0 + 1) / 3 = 0.66
Mumbai: (0 + 0) / 2 = 0.00
Pune: (1) / 1 = 1.00

| City   | Encoded Value |
| ------ | ------------- |
| Delhi  | 0.66          |
| Mumbai | 0.00          |
| Pune   | 1.00          |