# rondom forest

* Bagging (Bootstrap Aggregating) is an ensemble learning technique used to reduce variance and prevent overfitting by training multiple models on different random samples of the dataset.

Any number ≥ 2 models trained on different bootstrap samples is Bagging,
but usually 50–200 models are used in practice.

# 🔧 How Bagging Works (Step-by-step)
* Take bootstrap samples
* Randomly sample the dataset with replacement
* Each sample is slightly different
* Each has the same size as original dataset
* Train a separate model on each sample
* All models are trained independently
* Usually same algorithm (e.g., many Decision Trees)
* Combine predictions
* For classification → majority voting
* For regression → average prediction

# 🎯 Why Bagging is used?
* Reduces overfitting
* Reduces variance
* Increases accuracy
* Works best with high-variance models (like Decision Trees)

In [3]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('iris_sample_dataset.csv')
df

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0            6.8           3.2            5.9           2.3   Iris-virginica
1            6.9           3.1            5.1           2.3   Iris-virginica
2            4.9           3.0            1.4           0.2      Iris-setosa
3            5.6           3.0            4.5           1.5  Iris-versicolor
4            4.8           3.1            1.6           0.2      Iris-setosa
5            5.8           2.8            5.1           2.4   Iris-virginica
6            7.2           3.6            6.1           2.5   Iris-virginica
7            5.1           3.5            1.4           0.3      Iris-setosa
8            4.7           3.2            1.6           0.2      Iris-setosa
9            6.6           3.0            4.4           1.4  Iris-versicolor

In [4]:
le = LabelEncoder()
df['Species']= le.fit_transform(df['Species'])
df

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            6.8           3.2            5.9           2.3        2
1            6.9           3.1            5.1           2.3        2
2            4.9           3.0            1.4           0.2        0
3            5.6           3.0            4.5           1.5        1
4            4.8           3.1            1.6           0.2        0
5            5.8           2.8            5.1           2.4        2
6            7.2           3.6            6.1           2.5        2
7            5.1           3.5            1.4           0.3        0
8            4.7           3.2            1.6           0.2        0
9            6.6           3.0            4.4           1.4        1

In [5]:
x = df[['SepalLengthCm'	,'SepalWidthCm',	'PetalLengthCm',	'PetalWidthCm',	'Species']] # feautres 
y = df['Species'] # labels

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size= 0.3)

In [7]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100,criterion='gini')
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [8]:
rfc.predict(x_test)

array([1, 0, 2])

In [9]:
rfc.score(x_test,y_test)

0.6666666666666666

 # Hyper parmeter in random forest

# GridSearch CV

In [13]:
# Number of trees in random forest
n_estimators = [20,60,100,120]

# Number of features to consider at every split
max_features = [0.2,0.6,1.0]

# Maximum number of levels in tree
max_depth = [2,8,None]

# Number of samples
max_samples = [0.5,0.75,1.0]

# 108 diff random forest train

In [14]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples
             }
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0]}

In [15]:
rf =RandomForestClassifier()

In [16]:
from sklearn.model_selection import GridSearchCV
rf_grid = GridSearchCV(estimator=rf,
                      param_grid=param_grid,
                       cv=5,
                      verbose=2,
                      n_jobs= -1)

In [ ]:
rf_grid.fit(x_train,y_train)

In [22]:
GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 60, 100, 120]},
             verbose=2)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 60, 100, 120]},
             verbose=2)

In [24]:
# rf_grid.best_params_

# RandomzedSearch CV

# OOb evalution

In [25]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

	age	sex	cp	trestbps	chol	fbs	restecg	thalach	exang	oldpeak	slope	ca	thal	target
0	63	1	3	145	233	1	0	150	0	2.3	0	0	1	1
1	37	1	2	130	250	0	1	187	0	3.5	0	0	2	1
2	41	0	1	130	204	0	0	172	0	1.4	2	0	2	1
3	56	1	1	120	236	0	1	178	0	0.8	2	0	2	1
4	57	0	0	120	354	0	1	163	1	0.6	2	0	2	1

In [ ]:
df = pd.read_csv('heart.csv')
df.head()

In [28]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
rf = RandomForestClassifier(oob_score=True)

In [31]:
rf.fit(X_train,y_train)

RandomForestClassifier(oob_score=True)

In [32]:
rf.oob_score_

0.875

In [33]:
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

1.0